version: '3'
services:
  duologger:
    image: docker.otenv.com/duo_logger:1.0
    container_name: duo_logger
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "20"
    labels:
      com.duo.logger.owner: "Security Team"
      com.duo.logger.code.version: "v1.0"
      com.duo.logger.built: "Sun, 03 March 2019 00:00:00 -0000"
    volumes:
      - ./:/usr/src/app
volumes:
  data:
    driver: local
